package s2

import (
	"time"
)

type S2Server struct {
	Status           string    `json:"status"`
	IsApplied        int       `json:"is_applied"`
	Description      string    `json:"description"`
	SubCode          int       `json:"sub_code"`
	TransitionStatus string    `json:"transition_status"`
	Controller       string    `json:"controller"`
	ConsoleID        string    `json:"console_id"`
	InstanceID       string    `json:"instance_id"`
	ServiceType      string    `json:"service_type"`
	RootUserID       string    `json:"root_user_id"`
	CreateTime       time.Time `json:"create_time"`
	PrivateIP        string    `json:"private_ip"`
	S2ServerID       string    `json:"s2_server_id"`
	Memory           int       `json:"memory"`
	Owner            string    `json:"owner"`
	StatusTime       time.Time `json:"status_time"`
	CPU              int       `json:"cpu"`
	S2ServerType     int       `json:"s2_server_type"`
	VxnetID          string    `json:"vxnet_id"`
	Vxnet            struct {
		VxnetType   int    `json:"vxnet_type"`
		VxnetID     string `json:"vxnet_id"`
		Controller  string `json:"controller"`
		ConsoleID   string `json:"console_id"`
		VxnetName   string `json:"vxnet_name"`
		RootUserID  string `json:"root_user_id"`
		CreateTime  string `json:"create_time"`
		Owner       string `json:"owner"`
		Description string `json:"description"`
	} `json:"vxnet"`
	Name string `json:"name"`
}
type AutoGenerated struct {
	Username       string    `json:"username"`
	RootUserID     string    `json:"root_user_id"`
	S2ServerID     string    `json:"s2_server_id"`
	SharedTargetID string    `json:"shared_target_id"`
	ExportName     string    `json:"export_name"`
	Enabled        int       `json:"enabled"`
	TargetType     string    `json:"target_type"`
	ConsoleID      string    `json:"console_id"`
	Controller     string    `json:"controller"`
	CreateTime     time.Time `json:"create_time"`
	Volumes        struct {
	} `json:"volumes"`
	Owner       string `json:"owner"`
	Password    string `json:"password"`
	IPAddress   string `json:"ip_address"`
	Port        int    `json:"port"`
	Description string `json:"description"`
}

type S2DefaultParameters []struct {
	ServiceType  string `json:"service_type"`
	ParamName    string `json:"param_name"`
	DefaultValue string `json:"default_value"`
	TargetType   string `json:"target_type"`
	Description  string `json:"description"`
}
